# ################################
# Model: X-vector model for speaker recognition
# Authors: Nauman Dawalatabad & Mirco Ravanelli 2020
# ################################

seed: 1986
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Folders and train_log file
data_folder: /ldaphome/szaiem/voxceleb/
output_folder: results/voxceleb1_2/verification_discriminator_xvectors/
save_folder: !ref <output_folder>/save/
train_log: !ref <output_folder>/train_log.txt

# csv files
train_annotation: !ref <save_folder>/train.csv
valid_annotation: !ref <save_folder>/dev.csv
enrol_annotation: !ref <save_folder>/enrol.csv
test_annotation: !ref <save_folder>/test.csv

# Training hyperparameters
number_of_epochs: 25
batch_size: 128
lr: 0.0002500
lr_final: 0.00005000
freeze_embeddings: False
sentence_len: 3
sample_rate: 16000
random_chunk: False

# Pretrain from web (as an alternative specify a file)
pretrain_embeddings: True
embedding_file:
    #https://www.dropbox.com/s/p51au63q72jabqf/xvector_model.ckpt?dl=1 # vox1+2
    # https://www.dropbox.com/s/exzbyt4qoabo7v4/embedding_model.ckpt?dl=1 vox2
     https://www.dropbox.com/s/skfz2sme5nw7jji/xvector_model.ckpt?dl=1 # vox1

# Feature parameters
n_mels: 24
left_frames: 0
right_frames: 0
deltas: False

# Dataloader options
train_dataloader_opts:
    batch_size: !ref <batch_size>

valid_dataloader_opts:
    batch_size: !ref <batch_size>

enrol_dataloader_opts:
    batch_size: 1

test_dataloader_opts:
    batch_size: 1

# Functions
compute_features: !new:speechbrain.lobes.features.Fbank
    n_mels: !ref <n_mels>
    left_frames: !ref <left_frames>
    right_frames: !ref <right_frames>
    deltas: !ref <deltas>

embedding_model: !new:speechbrain.lobes.models.Xvector.Xvector
    in_channels: !ref <n_mels>
    activation: !name:torch.nn.LeakyReLU
    tdnn_blocks: 5
    tdnn_channels: [512, 512, 512, 512, 1500]
    tdnn_kernel_sizes: [5, 3, 3, 1, 1]
    tdnn_dilations: [1, 2, 3, 1, 1]
    lin_neurons: 512

discriminator: !new:speechbrain.lobes.models.Xvector.Discriminator
    activation: !name:torch.nn.LeakyReLU
    input_shape: [null, null, 1024]
    lin_blocks: 1
    lin_neurons: 4096
    out_neurons: 1

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

bn_emb: !new:speechbrain.nnet.normalization.BatchNorm1d
    input_size: 512

env_corrupt: !new:speechbrain.lobes.augment.EnvCorrupt
    openrir_folder: !ref <data_folder>
    openrir_max_noise_len: 3.0  # seconds
    reverb_prob: 1.0
    noise_prob: 1.0
    noise_snr_low: 0
    noise_snr_high: 15
    rir_scale_factor: 1.0

augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    sample_rate: !ref <sample_rate>
    speeds: [100]

modules:
    compute_features: !ref <compute_features>
    augmentation: !ref <augmentation>
    env_corrupt: !ref <env_corrupt>
    embedding_model: !ref <embedding_model>
    discriminator: !ref <discriminator>
    mean_var_norm: !ref <mean_var_norm>
    bn_emb: !ref <bn_emb>


epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

compute_cost: !name:speechbrain.nnet.losses.compute_masked_loss

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

lr_annealing: !new:speechbrain.nnet.schedulers.LinearScheduler
    initial_value: !ref <lr>
    final_value: !ref <lr_final>
    epoch_count: !ref <number_of_epochs>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        embedding_model: !ref <embedding_model>
        discriminator: !ref <discriminator>
        mean_var_norm: !ref <mean_var_norm>
        bn_emb: !ref <bn_emb>
        counter: !ref <epoch_counter>
